### ISSUE TITLE
Currently not open source - lacking a license file

### ISSUE THREAD

**Issue by 094459** [MetPhoto/Job-application-tracking-dataase#3]
This project is not currently open source as it lacks a license file in the root folder. I would recommend that you copy/add one based on what you want to achieve.

My recommendation would be to use something like MIT or Apache 2.0 - you can generate these via github i believe.

**Comment by MetPhoto** [comment]
Understood, I will add a license today.

**Comment by 094459** [comment]
MIT license, all good.
